In [15]:
my_list = [1,34,3,5,33,76,43]

In [16]:
import numpy as np

In [17]:
arr = np.array(my_list)
arr

array([ 1, 34,  3,  5, 33, 76, 43])

In [18]:
my_matrix = [[1,2,3],[3,4,5],[6,7,8]]

In [19]:
np.array(my_matrix)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.rand(5,5)

array([[0.95153474, 0.84108382, 0.29434541, 0.37767207, 0.59341454],
       [0.71202238, 0.10942397, 0.03708659, 0.8448407 , 0.54720887],
       [0.36523423, 0.33109784, 0.43833513, 0.4642887 , 0.26871655],
       [0.342194  , 0.92511538, 0.19339154, 0.08633984, 0.13703315],
       [0.38646575, 0.16450931, 0.70702189, 0.50590798, 0.19243255]])

In [36]:
np.random.randn(5,5)

array([[-0.16123393, -0.79113023, -1.12542234, -0.49189281,  0.34347873],
       [-0.14209904, -0.54079709,  0.50576332, -0.40885609, -0.71444837],
       [ 1.74415383,  0.50865232, -1.06515797, -1.22614197,  0.39068672],
       [ 2.13229456,  1.20310933, -0.20198876, -0.21075002,  1.06639737],
       [ 0.20410217, -0.09361916,  0.28917118,  0.54042936,  0.26838599]])

In [41]:
np.random.randint(1,100,10)

array([68, 64, 48, 10, 88, 67, 31, 43, 18, 15])

In [43]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
ran = np.random.randint(1,10,25)
ran

array([9, 5, 8, 6, 5, 1, 3, 6, 3, 7, 9, 6, 4, 4, 7, 9, 5, 7, 3, 5, 6, 2,
       8, 7, 4])

In [63]:
newRan = ran.reshape(5,5)

In [56]:
ran

array([9, 5, 8, 6, 5, 1, 3, 6, 3, 7, 9, 6, 4, 4, 7, 9, 5, 7, 3, 5, 6, 2,
       8, 7, 4])

In [61]:
ran.argmax()

0

In [64]:
newRan.shape

(5, 5)

In [66]:
newRan.dtype

dtype('int32')