In [1]:
import numpy as np

In [6]:
arr = np.arange(0,10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [14]:
for x in arr:
    if x > 5 :
        arr[x] = 110

In [15]:
arr

array([  0,   1,   2,   3,   4,   5, 110, 110, 110, 110])

In [17]:
arr[0:5] = 10

In [18]:
arr

array([ 10,  10,  10,  10,  10,   5, 110, 110, 110, 110])

In [19]:
arr[0:10] = 0

In [20]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
array_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
array_2d[0,0]

5

In [34]:
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr = np.arange(1,11)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [54]:
arr[arr<3]

array([1, 2])

In [55]:
array_2d = np.arange(50)

In [56]:
array_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [57]:
array_2d.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
sliceOfArray = arr[:5]

In [64]:
sliceOfArray

array([1, 2, 3, 4, 5])

In [65]:
sliceOfArray[:] = 999

In [66]:
sliceOfArray

array([999, 999, 999, 999, 999])

In [67]:
arr

array([999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [85]:
testArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
testArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
testArray[:2,1:]

array([[2, 3],
       [5, 6]])

In [88]:
testArray.reshape(5,10)

ValueError: cannot reshape array of size 9 into shape (5,10)

In [89]:
testArray = np.arange(50)

In [90]:
testArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [95]:
testArray.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [98]:
testArray[1:3]

array([1, 2])