In [1]:
import numpy as np

In [2]:
arr = np.ones(10)

In [3]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
arr = np.zeros(10)

In [5]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr = np.arange(5,10)

In [11]:
arr = np.array(5)

TypeError: Cannot interpret '1' as a data type

In [9]:
arr

array(5)

In [15]:
np.array()

array([5, 6, 7, 8, 9])

In [17]:
np.ones(5) * 5

array([5., 5., 5., 5., 5.])

In [18]:
np.zeros(5) + 5

array([5., 5., 5., 5., 5.])

In [19]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
arr = np.arange(10,50)

In [22]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [24]:
positiveArray = arr + arr

In [25]:
positiveArray

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [50]:
np.random.random_integers(1,2)

C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  """Entry point for launching an IPython kernel.


2

In [52]:
np.random.rand(2)

array([0.18369516, 0.69618943])

In [58]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.random.random_sample(25)

array([0.52518362, 0.65979764, 0.69605385, 0.10181811, 0.19137036,
       0.34132405, 0.55960239, 0.78846769, 0.35778817, 0.47513159,
       0.13395177, 0.15382183, 0.71862534, 0.20324102, 0.03794677,
       0.91446914, 0.75840483, 0.49058935, 0.52553696, 0.56713087,
       0.08761798, 0.80843612, 0.36754286, 0.84817896, 0.90779083])

In [65]:
np.arange(0.01,1,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [66]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [73]:
mat = np.arange(1,26).reshape(5,5)

In [74]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
newMat = mat[2:,1:]

In [81]:
newMat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [83]:
newMat[1][3]

20

In [84]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
x = mat[:3,1:2]
x

array([[ 2],
       [ 7],
       [12]])

In [94]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [99]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [100]:
np.sum(mat)

325

In [101]:
np.std(mat)

7.211102550927978

In [104]:
mat.sum(0)

array([55, 60, 65, 70, 75])